```{r }
library("tidyverse")
```


# Ejercicio 1
## a)

```{r 1a}
#llamar función para pruebas binomiales
```

## b)

```{r 1b}

potencia_dada_normal <- 1 - pbinom(size=10,
                                   prob=1-pnorm(0,1,1),
                                   q=7)

potencia_dada_normal



potencia_dada_dexp <- 1 - pbinom(size=10,
                                 prob = 0.8160,
                                 q=7)

potencia_dada_dexp

```


```{r 1c}
k_1c <- 5 + pnorm(0.025)*sqrt(2.5)

k_1c

potencia_corregida_asint <- 1 - pbinom(
  prob = 1 - pnorm(0,1,1),
  size=10,
  q = 6
)

potencia_corregida_asint
```

# 2

## a)
```{r pájaros 1a}
pajaros <- c( 8,10,38, 43, 45, 57,  73, 76, 83, 105, 112, 126, 141 )

pajCentrados <- pajaros - 90

estadS <- map_lgl(pajCentrados, ~.x>0) %>% sum() 

estadS
```

# 3

```{r pajaros}
obs3 <- c(8,
          10,
          38,
          43,
          45,
          57,
          73,
          76,
          83,
          105,
          112,
          126,
          141)

obs3Centradas <- obs3 -90

tObs <- sum(obs3Centradas > 0)

tObs

pruebaAsint <- function(n,p0,alfa) {
  zeta <- pnorm(alfa/2)
  return( n/2 - zeta * sqrt(n / 4) )
}


kprueba3 <- pruebaAsint(13,0.5,0.05)

kprueba3

intAsint <- function(n,p0,alfa) {
  zeta <- qnorm(1 - alfa/2)
  delta <- zeta * sqrt( n * p0 * (1 - p0) )
  return(
    list(
      "inf" = n * p0 - delta + 1,
      "sup" = n * p0 + delta + 1

    )
  )
}

obs3Ordenadas <- sort(obs3)

obs3Ordenadas[[7]]

kintervalo3 <- pbinom

obs3Ordenadas[[4]]
obs3Ordenadas[[10]]

```


## 5 

```{r estudiantes}


tabla5 <- tribble(~Estudiante, ~Antes, ~Después,
"A", 174, 165,
"E", 191, 186,
"J" ,188 , 183,
"M" ,182 ,178,
"P" ,201 ,203,
"R" ,188 ,181 )

tabla5 <- tabla5 %>% mutate( signo = sign(Después - Antes)   )

tabla5

```

# Ejercicio 7

```{r }

t1 <- 1/11

t1

pvalorA <- pbinom(size = 66, p = 0.5, q=40)

pvalorA

pvalorB <- 1 - pbinom(size = 66, p = 0.5, q=40)

pvalorB

pbinom(size = 66, p = 0.5, q=26)

k <- 26
# para el aproximado
qchisq(df=1,p=0.05)

```


## Ejercicio 8

```{r accidentes}

datos8 <- c(17.3 ,
           17.9 ,
           18.4 ,
           18.1 ,
           18.3 ,
           19.6 ,
           18.6 ,
           19.2 ,
           17.7 ,
           20.0 ,
           19.0 ,
           18.8 ,
           19.3 ,
           20.2 ,
           19.9 )

length(datos8)

tabla8 <- tibble( "antes" = datos8[seq(1,7)], "después" = datos8[seq(9,15)] )

tabla8 %>% mutate( diferencia = después - antes ) -> tabla8


tabla8

tObs <- (tabla8$diferencia > 0) %>% sum()

tObs

pbinom(size = 15, p = 0.5, q = 5)

```


## Ejercicio 9

```{r }
antes <-c( 68.3, 68.6, 68.4, 68.1, 68.4, 68.2, 68.7, 68.9, 69.0, 68.8, 69.0, 68.6, 69.2, 69.2, 68.9, 68.6, 68.6 )
despues <- c( 68.8, 69.2, 68.8, 68.7, 69.5, 68.7, 68.8, 69.4, 69.3, 69.3, 69.5, 69.5, 69.0, 69.2, 69.2, 69.1, 69.9)

tabla9 <- tibble(
  antes,
  despues,
  diferencia = despues - antes
)


tabla9

tabla9SE <- tabla9[-14,]

tabla9SE

tObs <- (tabla9SE$diferencia > 0) %>% sum()

tObs
```

## 10 Líneas

```{r líneas}

tabla10 <- tribble ( ~"línea", ~A, ~B,
1, 0.3, -0.1,
11 , -1.3, -0.6,
2 , 1.1 , 0.6 ,
12 , -1.1 , -1.2 ,
3 , 0.9 , 1.0 ,
13 , -1.3 , -1.0 ,
4 , 0.6 , 0.7 ,
14 , -0.7 , -0.7 ,
5 , 1.0 , 0.2 ,
15 , -1.4 , -0.7 ,
6 , 1.3 , 0.9 ,
16 , -1.4 , -0.1 ,
7 , 0.8 , -0.1 ,
17 , -0.8 , -0.5 ,
8 , 1.6 , 0.2 ,
18  ,-0.5  ,0.0,
9, 1.2 , 0.0 ,
19 , -1.2 , -0.4 ,
10 , 0.8 , 0.5 ,
20  , -1.0 , -0.3)



Bordenado <- sort(tabla10$B)

OrdenPorB <- map(Bordenado, ~which( tabla10$B == .x ))

indicesOrdenPorB <- OrdenPorB
indicesOrdenPorB[[3]] <- 14
indicesOrdenPorB[[4]] <- 15
indicesOrdenPorB[[9]] <- 1
indicesOrdenPorB[[10]] <- 7
indicesOrdenPorB[[11]] <- 16
indicesOrdenPorB[[12]] <- 9
indicesOrdenPorB[[13]] <- 18
indicesOrdenPorB[[14]] <- 5
indicesOrdenPorB[[15]] <- 8

indicesOrdenPorB <- as.double(indicesOrdenPorB)

tabla10Ord <- tabla10[indicesOrdenPorB,]

tablaPrueba <- tibble( antes = (tabla10Ord$A)[seq(1,10)],
                      despues = (tabla10Ord$A)[seq(11,20)],
                      diferencia = despues - antes
                      )

tablaPrueba

tObs <- (tablaPrueba$diferencia > 0) %>% sum()

```


## 11

```{r inmunes}

tabla11 <- tribble(~Vol, ~semana0, ~semana4, ~diferencia,
1, 0.4, 0.4, 0.0,
2, 0.4, 0.5, 0.1,
3, 0.4, 0.5, 0.1,
4, 0.4, 0.9, 0.5,
5, 0.5, 0.5, 0.0,
6, 0.5, 0.5, 0.0,
7, 0.5, 0.5, 0.0,
8, 0.5, 0.5, 0.0,
9, 0.5, 0.5, 0.0,
10, 0.6, 0.6, 0.0,
11,  0.6, 12.2, 11.6,
12, 0.7, 1.1, 0.4,
13, 0.7, 1.2, 0.5,
14, 0.8, 0.8, 0.0,
15, 0.9, 1.2, 0.3,
16, 0.9, 1.9, 1,
17, 1.0, 0.9, -0.1,
18, 1.0, 2.0, 1,
19, 1.6, 8.1, 6.5,
20, 2.0, 3.7, 1.7)

tabla11

nPrima <- (tabla11$diferencia != 0) %>% sum()

nPrima


tObs <- (tabla11$diferencia > 0) %>% sum()


tObs
```

